INSERT INTO usuario (ID, IS_ATIVO, LOGIN,NOME, SENHA,CREATED_AT, UPDATED_AT, VERSION) VALUES (1,true,'ADMIN','CRISTIANO','$2a$10$XhGlYKF2gBb15sSmTmXBt.D.X/C5ETFe8CL6mCEN91H2c91nCDIo6',current_timestamp(),current_timestamp(),1);
INSERT INTO usuario (ID, IS_ATIVO, LOGIN,NOME, SENHA,CREATED_AT, UPDATED_AT, VERSION) VALUES (2,true,'bruno','BRUNO','$2a$10$XhGlYKF2gBb15sSmTmXBt.D.X/C5ETFe8CL6mCEN91H2c91nCDIo6',current_timestamp(),current_timestamp(),1);


INSERT INTO role (ID, DESCRICAO,NOME,CREATED_AT, UPDATED_AT, VERSION) VALUES (1, 'USUARIOS COMUNS', 'USER',current_timestamp(),current_timestamp(),1);
INSERT INTO role (ID, DESCRICAO,NOME,CREATED_AT, UPDATED_AT, VERSION) VALUES (2, 'USUARIOS COMUNS', 'ADMIN',current_timestamp(),current_timestamp(),1);

INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID,CREATED_AT, UPDATED_AT, VERSION) VALUES (1,1,current_timestamp(),current_timestamp(),1);
INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID,CREATED_AT, UPDATED_AT, VERSION) VALUES (1,2,current_timestamp(),current_timestamp(),1);
INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID,CREATED_AT, UPDATED_AT, VERSION) VALUES (2,2,current_timestamp(),current_timestamp(),1);


INSERT INTO permissao (ID, NOME, DESCRICAO,CREATED_AT, UPDATED_AT, VERSION) VALUES(1, 'ROLE_CADASTROUSUARIO', 'CADASTRO DE NOVOS USUÁRIOS',current_timestamp(),current_timestamp(),1);
INSERT INTO permissao (ID, NOME, DESCRICAO,CREATED_AT, UPDATED_AT, VERSION) VALUES(2, 'ROLE_CONSULTAUSUARIO', 'CONSULTA USUÁRIOS',current_timestamp(),current_timestamp(),1);
INSERT INTO permissao (ID, NOME, DESCRICAO,CREATED_AT, UPDATED_AT, VERSION) VALUES(3, 'ROLE_ADMIN', 'ADMINISTRAÇÃO COMPLETA',current_timestamp(),current_timestamp(),1);

INSERT INTO pessoa (TIPO,ID,NOME , SOBRE_NOME, CPF,EMAIL, LOGRADOURO , NUMERO ,CIDADE, UF ,TEL_CEL , TEL_FIXO , USER ,CREATED_AT,UPDATED_AT, VERSION )
VALUES ('F',1,'CRISTIANO', 'BRAGA FURTADO', '080.587.317-14','cribraga@gmail.com', 'VILA GUILHERME', 222, 'PETRÓPOLIS','RJ','(21)995963227',
'(21)222222','ADMIN', current_timestamp(),current_timestamp(),1);