INSERT INTO usuario (ID, IS_ATIVO, LOGIN,NOME, SENHA) VALUES (1,true,'ADMIN','CRISTIANO','$2a$10$XhGlYKF2gBb15sSmTmXBt.D.X/C5ETFe8CL6mCEN91H2c91nCDIo6');
INSERT INTO usuario (ID, IS_ATIVO, LOGIN,NOME, SENHA) VALUES (2,true,'bruno','BRUNO','$2a$10$XhGlYKF2gBb15sSmTmXBt.D.X/C5ETFe8CL6mCEN91H2c91nCDIo6');


INSERT INTO role (ID, DESCRICAO,NOME) VALUES (1, 'USUARIOS COMUNS', 'USER');
INSERT INTO role (ID, DESCRICAO,NOME) VALUES (2, 'USUARIOS COMUNS', 'ADMIN');

INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID) VALUES (1,1);
INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID) VALUES (1,2);
INSERT INTO usuario_roles (USUARIO_ID, ROLES_ID) VALUES (2,2);



INSERT INTO permissao (ID, NOME, DESCRICAO) VALUES(1, 'ROLE_CADASTROUSUARIO', 'CADASTRO DE NOVOS USUÁRIOS');
INSERT INTO permissao (ID, NOME, DESCRICAO) VALUES(2, 'ROLE_CONSULTAUSUARIO', 'CONSULTA USUÁRIOS');
INSERT INTO permissao (ID, NOME, DESCRICAO) VALUES(3, 'ROLE_ADMIN', 'ADMINISTRAÇÃO COMPLETA');

INSERT INTO pessoa  (TIPO,ID,NOME , SOBRE_NOME, CPF,EMAIL, LOGRADOURO , NUMERO ,CIDADE, UF ,TEL_CEL , TEL_FIXO , USER ,DATE_UPDATE )
VALUES ('F',1,'CRISTIANO', 'BRAGA FURTADO', '080.587.317-14','cribraga@gmail.com', 'VILA GUILHERME', 222, 'PETRÓPOLIS','RJ','(21)995963227',
'(21)222222','ADMIN', current_timestamp());